CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE TABLE "DeviceCodes" (
        "UserCode" character varying(200) NOT NULL,
        "DeviceCode" character varying(200) NOT NULL,
        "SubjectId" character varying(200),
        "SessionId" character varying(100),
        "ClientId" character varying(200) NOT NULL,
        "Description" character varying(200),
        "CreationTime" timestamp with time zone NOT NULL,
        "Expiration" timestamp with time zone NOT NULL,
        "Data" character varying(50000) NOT NULL,
        CONSTRAINT "PK_DeviceCodes" PRIMARY KEY ("UserCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE TABLE "Keys" (
        "Id" text NOT NULL,
        "Version" integer NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Use" text,
        "Algorithm" character varying(100) NOT NULL,
        "IsX509Certificate" boolean NOT NULL,
        "DataProtected" boolean NOT NULL,
        "Data" text NOT NULL,
        CONSTRAINT "PK_Keys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE TABLE "PersistedGrants" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(200),
        "Type" character varying(50) NOT NULL,
        "SubjectId" character varying(200),
        "SessionId" character varying(100),
        "ClientId" character varying(200) NOT NULL,
        "Description" character varying(200),
        "CreationTime" timestamp with time zone NOT NULL,
        "Expiration" timestamp with time zone,
        "ConsumedTime" timestamp with time zone,
        "Data" character varying(50000) NOT NULL,
        CONSTRAINT "PK_PersistedGrants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE TABLE "PushedAuthorizationRequests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReferenceValueHash" character varying(64) NOT NULL,
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "Parameters" text NOT NULL,
        CONSTRAINT "PK_PushedAuthorizationRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE TABLE "ServerSideSessions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(100) NOT NULL,
        "Scheme" character varying(100) NOT NULL,
        "SubjectId" character varying(100) NOT NULL,
        "SessionId" character varying(100),
        "DisplayName" character varying(100),
        "Created" timestamp with time zone NOT NULL,
        "Renewed" timestamp with time zone NOT NULL,
        "Expires" timestamp with time zone,
        "Data" text NOT NULL,
        CONSTRAINT "PK_ServerSideSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_DeviceCodes_DeviceCode" ON "DeviceCodes" ("DeviceCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_DeviceCodes_Expiration" ON "DeviceCodes" ("Expiration");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_Keys_Use" ON "Keys" ("Use");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_ConsumedTime" ON "PersistedGrants" ("ConsumedTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_Expiration" ON "PersistedGrants" ("Expiration");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_PersistedGrants_Key" ON "PersistedGrants" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_SubjectId_ClientId_Type" ON "PersistedGrants" ("SubjectId", "ClientId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_PersistedGrants_SubjectId_SessionId_Type" ON "PersistedGrants" ("SubjectId", "SessionId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_PushedAuthorizationRequests_ExpiresAtUtc" ON "PushedAuthorizationRequests" ("ExpiresAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_PushedAuthorizationRequests_ReferenceValueHash" ON "PushedAuthorizationRequests" ("ReferenceValueHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_DisplayName" ON "ServerSideSessions" ("DisplayName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_Expires" ON "ServerSideSessions" ("Expires");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE UNIQUE INDEX "IX_ServerSideSessions_Key" ON "ServerSideSessions" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_SessionId" ON "ServerSideSessions" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    CREATE INDEX "IX_ServerSideSessions_SubjectId" ON "ServerSideSessions" ("SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809130438_AddDuendeOperationalStore') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260809130438_AddDuendeOperationalStore', '9.0.16');
    END IF;
END $EF$;
COMMIT;

