CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "InboxState" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageId" uuid NOT NULL,
        "ConsumerId" uuid NOT NULL,
        "LockId" uuid NOT NULL,
        "RowVersion" bytea,
        "Received" timestamp with time zone NOT NULL,
        "ReceiveCount" integer NOT NULL,
        "ExpirationTime" timestamp with time zone,
        "Consumed" timestamp with time zone,
        "Delivered" timestamp with time zone,
        "LastSequenceNumber" bigint,
        CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "Orders" (
        "Id" uuid NOT NULL,
        "CustomerId" bigint NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        "SubTotal" bigint NOT NULL,
        "ShippingFee" bigint NOT NULL,
        "TotalDiscount" bigint NOT NULL,
        "GrandTotal" bigint NOT NULL,
        "ShippingAddress" character varying(500) NOT NULL,
        "RecipientName" text NOT NULL,
        "RecipientPhone" text NOT NULL,
        "RecipientWardId" bigint NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "OutboxState" (
        "OutboxId" uuid NOT NULL,
        "LockId" uuid NOT NULL,
        "RowVersion" bytea,
        "Created" timestamp with time zone NOT NULL,
        "Delivered" timestamp with time zone,
        "LastSequenceNumber" bigint,
        CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "ShippingAddresses" (
        "Id" uuid NOT NULL,
        "CustomerId" bigint NOT NULL,
        "RecipientName" character varying(100) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Province" character varying(100) NOT NULL,
        "District" character varying(100) NOT NULL,
        "Ward" character varying(100) NOT NULL,
        "AddressLine" character varying(255) NOT NULL,
        "IsDefault" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_ShippingAddresses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "SubOrderSagaStates" (
        "CorrelationId" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "CurrentState" text NOT NULL,
        "ShopId" bigint NOT NULL,
        "CustomerId" bigint NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "IsOnlinePayment" boolean NOT NULL,
        "FailureReason" character varying(255),
        "RefundRequestId" uuid,
        "ItemsJson" text,
        "ShippingAddress" character varying(500),
        "RecipientName" text NOT NULL,
        "RecipientPhone" text NOT NULL,
        "RecipientWardId" bigint NOT NULL,
        "Weight" double precision NOT NULL,
        "Height" double precision NOT NULL,
        "Width" double precision NOT NULL,
        "Length" double precision NOT NULL,
        CONSTRAINT "PK_SubOrderSagaStates" PRIMARY KEY ("CorrelationId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "SubOrders" (
        "Id" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "CustomerId" bigint NOT NULL,
        "ShopId" bigint NOT NULL,
        "SubTotal" bigint NOT NULL,
        "ShippingFee" bigint NOT NULL,
        "SellerDiscount" bigint NOT NULL,
        "PlatformDiscount" bigint NOT NULL,
        "GrandTotal" bigint NOT NULL,
        "Status" integer NOT NULL,
        "IsOnlinePayment" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        "DeliveredDate" timestamp with time zone,
        CONSTRAINT "PK_SubOrders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubOrders_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "OutboxMessage" (
        "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EnqueueTime" timestamp with time zone,
        "SentTime" timestamp with time zone NOT NULL,
        "Headers" text,
        "Properties" text,
        "InboxMessageId" uuid,
        "InboxConsumerId" uuid,
        "OutboxId" uuid,
        "MessageId" uuid NOT NULL,
        "ContentType" character varying(256) NOT NULL,
        "MessageType" text NOT NULL,
        "Body" text NOT NULL,
        "ConversationId" uuid,
        "CorrelationId" uuid,
        "InitiatorId" uuid,
        "RequestId" uuid,
        "SourceAddress" character varying(256),
        "DestinationAddress" character varying(256),
        "ResponseAddress" character varying(256),
        "FaultAddress" character varying(256),
        "ExpirationTime" timestamp with time zone,
        CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
        CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES "InboxState" ("MessageId", "ConsumerId"),
        CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES "OutboxState" ("OutboxId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "OrderItems" (
        "Id" uuid NOT NULL,
        "SubOrderId" uuid NOT NULL,
        "VariantId" uuid NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "ProductName" character varying(255) NOT NULL,
        "VariantName" text NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_SubOrders_SubOrderId" FOREIGN KEY ("SubOrderId") REFERENCES "SubOrders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE TABLE "RefundRequests" (
        "Id" uuid NOT NULL,
        "SubOrderId" uuid NOT NULL,
        "CustomerId" bigint NOT NULL,
        "ShopId" bigint NOT NULL,
        "RefundAmount" numeric(18,2) NOT NULL,
        "Reason" character varying(1000) NOT NULL,
        "SellerNote" character varying(1000),
        "Status" integer NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_RefundRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefundRequests_SubOrders_SubOrderId" FOREIGN KEY ("SubOrderId") REFERENCES "SubOrders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_InboxState_Delivered" ON "InboxState" ("Delivered");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_OrderItems_SubOrderId" ON "OrderItems" ("SubOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON "OutboxMessage" ("OutboxId", "SequenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_OutboxState_Created" ON "OutboxState" ("Created");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_RefundRequests_SubOrderId" ON "RefundRequests" ("SubOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    CREATE INDEX "IX_SubOrders_OrderId" ON "SubOrders" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112508_InitialOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260801112508_InitialOrder', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260808090134_AddThumbnailUrl') THEN
    ALTER TABLE "OrderItems" ADD "ThumbnailUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260808090134_AddThumbnailUrl') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260808090134_AddThumbnailUrl', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812141646_AddVoucher') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812141646_AddVoucher', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814150803_AddVoucher2') THEN
    CREATE TABLE "Vouchers" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" text NOT NULL,
        "DiscountType" integer NOT NULL,
        "DiscountValue" numeric(18,2) NOT NULL,
        "Scope" integer NOT NULL,
        "MinOrderValue" numeric NOT NULL,
        "MaxUsageCount" bigint NOT NULL,
        "UsageCount" bigint NOT NULL,
        "MaxUsagePerUser" bigint NOT NULL,
        "MaxDiscountAmount" numeric(18,2),
        "ShopId" bigint,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedByUserId" bigint,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_Vouchers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814150803_AddVoucher2') THEN
    CREATE TABLE "VoucherUsages" (
        "Id" uuid NOT NULL,
        "VoucherId" uuid NOT NULL,
        "UserId" bigint NOT NULL,
        "OrderId" uuid,
        "SubOrderId" uuid,
        "DiscountAmount" numeric NOT NULL,
        "UsedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VoucherUsages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VoucherUsages_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814150803_AddVoucher2') THEN
    CREATE INDEX "IX_VoucherUsages_VoucherId" ON "VoucherUsages" ("VoucherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814150803_AddVoucher2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260814150803_AddVoucher2', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815065635_AddVoucherIdsToSubOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260815065635_AddVoucherIdsToSubOrder', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815080131_AddVoucherForSubOrder') THEN
    ALTER TABLE "SubOrders" ADD "PlatformVoucherId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815080131_AddVoucherForSubOrder') THEN
    ALTER TABLE "SubOrders" ADD "ShopVoucherId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815080131_AddVoucherForSubOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260815080131_AddVoucherForSubOrder', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142331_AddproductId') THEN
    ALTER TABLE "SubOrders" ALTER COLUMN "Status" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142331_AddproductId') THEN
    ALTER TABLE "RefundRequests" ALTER COLUMN "Status" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142331_AddproductId') THEN
    ALTER TABLE "OrderItems" ADD "ProductId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142331_AddproductId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260817142331_AddproductId', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818132311_AddImagesForRefund') THEN
    ALTER TABLE "RefundRequests" ADD "Medias" text[] NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818132311_AddImagesForRefund') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260818132311_AddImagesForRefund', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821070921_VoucherStatus') THEN
    ALTER TABLE "Vouchers" ALTER COLUMN "Scope" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821070921_VoucherStatus') THEN
    ALTER TABLE "Vouchers" ALTER COLUMN "DiscountType" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821070921_VoucherStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260821070921_VoucherStatus', '9.0.16');
    END IF;
END $EF$;
COMMIT;

