CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "InboxState" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageId" uuid NOT NULL,
        "ConsumerId" uuid NOT NULL,
        "LockId" uuid NOT NULL,
        "RowVersion" bytea,
        "Received" timestamp with time zone NOT NULL,
        "ReceiveCount" integer NOT NULL,
        "ExpirationTime" timestamp with time zone,
        "Consumed" timestamp with time zone,
        "Delivered" timestamp with time zone,
        "LastSequenceNumber" bigint,
        CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "OutboxState" (
        "OutboxId" uuid NOT NULL,
        "LockId" uuid NOT NULL,
        "RowVersion" bytea,
        "Created" timestamp with time zone NOT NULL,
        "Delivered" timestamp with time zone,
        "LastSequenceNumber" bigint,
        CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "PaymentMethods" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "SubTitle" text,
        "IsActive" boolean NOT NULL,
        "ProviderName" text NOT NULL,
        "IconUrl" text NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "Wallets" (
        "Id" uuid NOT NULL,
        "UserId" bigint NOT NULL,
        "Balance" numeric(18,2) NOT NULL,
        "IsLocked" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_Wallets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "OutboxMessage" (
        "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EnqueueTime" timestamp with time zone,
        "SentTime" timestamp with time zone NOT NULL,
        "Headers" text,
        "Properties" text,
        "InboxMessageId" uuid,
        "InboxConsumerId" uuid,
        "OutboxId" uuid,
        "MessageId" uuid NOT NULL,
        "ContentType" character varying(256) NOT NULL,
        "MessageType" text NOT NULL,
        "Body" text NOT NULL,
        "ConversationId" uuid,
        "CorrelationId" uuid,
        "InitiatorId" uuid,
        "RequestId" uuid,
        "SourceAddress" character varying(256),
        "DestinationAddress" character varying(256),
        "ResponseAddress" character varying(256),
        "FaultAddress" character varying(256),
        "ExpirationTime" timestamp with time zone,
        CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
        CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES "InboxState" ("MessageId", "ConsumerId"),
        CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES "OutboxState" ("OutboxId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "Payments" (
        "Id" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "OrderId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "MethodId" bigint NOT NULL,
        "ErrorMessage" text,
        "GatewayTransactionId" text,
        "PaymentUrl" text,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_PaymentMethods_MethodId" FOREIGN KEY ("MethodId") REFERENCES "PaymentMethods" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "BankAccounts" (
        "Id" uuid NOT NULL,
        "WalletId" uuid NOT NULL,
        "BankName" text NOT NULL,
        "BankAccountNumber" text NOT NULL,
        "BankAccountHolder" text NOT NULL,
        "IsDefault" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_BankAccounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BankAccounts_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "WalletTransactions" (
        "Id" uuid NOT NULL,
        "WalletId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Type" integer NOT NULL,
        "Reason" integer NOT NULL,
        "BalanceAfter" numeric(18,2) NOT NULL,
        "ReferenceId" uuid,
        "Description" text,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_WalletTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WalletTransactions_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE TABLE "WithdrawalRequests" (
        "Id" uuid NOT NULL,
        "WalletId" uuid NOT NULL,
        "UserId" bigint NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "BankAccountId" uuid NOT NULL,
        "BankName" text NOT NULL,
        "BankAccountNumber" text NOT NULL,
        "BankAccountHolder" text NOT NULL,
        "Status" integer NOT NULL,
        "AdminNote" text,
        "ProcessedByAdminId" bigint,
        "ProcessedAt" timestamp with time zone,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_WithdrawalRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WithdrawalRequests_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_BankAccounts_WalletId" ON "BankAccounts" ("WalletId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_InboxState_Delivered" ON "InboxState" ("Delivered");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON "OutboxMessage" ("OutboxId", "SequenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_OutboxState_Created" ON "OutboxState" ("Created");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_Payments_MethodId" ON "Payments" ("MethodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE UNIQUE INDEX "IX_Wallets_UserId" ON "Wallets" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_WalletTransactions_WalletId" ON "WalletTransactions" ("WalletId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    CREATE INDEX "IX_WithdrawalRequests_WalletId" ON "WithdrawalRequests" ("WalletId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112425_InitialPayment') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260801112425_InitialPayment', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815140613_AddProofImage') THEN
    ALTER TABLE "WithdrawalRequests" ADD "ProofImageUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260815140613_AddProofImage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260815140613_AddProofImage', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142154_AddProductId') THEN
    ALTER TABLE "WithdrawalRequests" ALTER COLUMN "Status" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142154_AddProductId') THEN
    ALTER TABLE "Payments" ALTER COLUMN "Status" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142154_AddProductId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260817142154_AddProductId', '9.0.16');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260817142922_UpdateStatusEnumToString') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260817142922_UpdateStatusEnumToString', '9.0.16');
    END IF;
END $EF$;
COMMIT;

