<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BuildingBlocks.Messaging</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.3.6" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BuildingBlocks.Shared\BuildingBlocks.Shared.csproj" />
      <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    </ItemGroup>

</Project>
