<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Cors\" />
      <Folder Include="Extensions\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BuildingBlocks.Shared\BuildingBlocks.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.OpenApi" Version="1.6.17" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.0.7" />
    </ItemGroup>

</Project>
