<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
      <PackageReference Include="Grpc.Tools" Version="2.81.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <!-- Chỉ định file .proto để tự sinh cả Client và Server C# code -->
        <Protobuf Include="Protos\product.proto" GrpcServices="Both" />
        <Protobuf Include="Protos\cart.proto" GrpcServices="Both" />
        <Protobuf Include="Protos\payment.proto" GrpcServices="Both" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BuildingBlocks.Shared\BuildingBlocks.Shared.csproj" />
    </ItemGroup>

</Project>
