syntax = "proto3";

option csharp_namespace = "BuildingBlocks.Grpc.Services";

package cart;

service CartGrpc {
  rpc GetCartByCustomerId(GetCartByIdRequest) returns (GetCartByIdResponse);
  rpc ClearCart(ClearCartRequest) returns (ClearCartResponse);
}

message GetCartByIdRequest {
  int64 customer_id = 1;
}

message RpcCartItemDto {
  string variantId = 1;
  int32 quantity = 7;
  bool isSelected = 8;
  string productId = 9;
  string productName = 10;
  string variantName = 11;
  string unitPrice = 12;
  int64 shopId = 13;
  int32 availableStocks = 14;
  double weight = 15;
  double length = 16;
  double width = 17;
  double height = 18;
  string thumbnailUrl = 19;
} 

message GetCartByIdResponse {
  int64 customer_id = 1;
  repeated RpcCartItemDto items = 2;
}

message ClearCartRequest {
  int64 customer_id = 1;
  repeated string variant_ids = 2;
}

message ClearCartResponse {
  bool is_success = 1;
  string error_message = 2;
}
