syntax = "proto3";

option csharp_namespace = "BuildingBlocks.Grpc.Services";

package product;

service ProductGrpc {
  rpc GetVariantById(GetVariantByIdRequest) returns (GetVariantByIdResponse);
  rpc GetVariantsByIds(GetVariantsByIdsRequest) returns (GetVariantsByIdsResponse);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
}

//
message GetVariantByIdRequest {
  int64 id = 1;
}

message GetVariantByIdResponse {
  int64 variantId = 1;
  int32 availableStock = 2;
  int64 shopId = 3;
  int64 productId = 4;
}

//
message GetVariantsByIdsRequest {
  repeated int64 variantIds = 1;
  repeated int64 productIds = 2;
}

message GetVariantsByIdsResponse {
  repeated RpcVariantDto Variants = 1;
}

message RpcVariantDto {
  int64 variantId = 1;
  int64 productId = 2;
  string productName = 3;
  string variantName = 4;
  string unitPrice = 5;
  int32 availableStock = 6;
  int64 shopId = 7;
  double weight = 8;
  double length = 9;
  double width = 10;
  double height = 11;
  string thumbnailUrl = 12;
  string discountPrice = 13;
}

message ReserveStockRequest {
  repeated RpcReserveStockItemDto items = 1;
}

message RpcReserveStockItemDto {
  int64 variantId = 1;
  int32 quantity = 2;
  int64 productId = 3;
}

message ReserveStockResponse {
  bool isSuccess = 1;
  string errorMessage = 3;
}
