syntax = "proto3";

option csharp_namespace = "BuildingBlocks.Grpc.Services";

package product;

service ProductGrpc {
  rpc GetVariantById(GetVariantByIdRequest) returns (GetVariantByIdResponse);
  rpc GetVariantsByIds(GetVariantsByIdsRequest) returns (GetVariantsByIdsResponse);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
}


//
message  GetVariantByIdRequest {
  string id = 1;
}

message  GetVariantByIdResponse {
  string variantId = 1;
  int32 availableStocks = 2;
  int64 shopId = 3;
}

//
message GetVariantsByIdsRequest {
  repeated string variantIds = 1;
  repeated string productIds = 2;
}
message GetVariantsByIdsResponse {
  repeated RpcVariantDto Variants = 1;
}

message RpcVariantDto {
  string variantId = 1;
  string productId = 2;
  string productName = 3;
  string variantName = 4;
  string unitPrice = 5;
  int32 availableStocks = 6;
  int64 shopId = 7;
  double weight = 8;
  double length = 9;
  double width = 10;
  double height = 11;
  string thumbnailUrl = 12;
  string discountPrice = 13;
}

message ReserveStockRequest {
  repeated RpcReserveStockItemDto items = 1;
}

message RpcReserveStockItemDto {
  string variantId = 1;
  int32 quantity = 2;
}

message ReserveStockResponse {
  bool isSuccess = 1;
  string errorMessage = 3;
}
