syntax = "proto3";

option csharp_namespace = "BuildingBlocks.Grpc.Services";

package product;

service ProductGrpc {
  rpc GetVariantById(GetVariantByIdRequest) returns (GetVariantByIdResponse);
  rpc GetVariantsByIds(GetVariantsByIdsRequest) returns (GetVariantsByIdsResponse);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
}


//
message  GetVariantByIdRequest {
  string id = 1;
}

message  GetVariantByIdResponse {
  string variantId = 1;
  int32 availableStocks = 2;
  int64 shopId = 3;
}

//
message GetVariantsByIdsRequest {
  repeated string variantIds = 1;
}
message GetVariantsByIdsResponse {
  repeated RpcVariantDto Variants = 1;
}

message RpcVariantDto {
  string variantId = 1;
  string productId = 2;
  string productName = 3;
  string variantName = 4;
  string unitPrice = 5;
  int32 availableStocks = 6;
  int64 shopId = 7;
}

message ReserveStockRequest {
  repeated RpcReserveStockItemDto items = 1;
}

message RpcReserveStockItemDto {
  string variantId = 1;
  int32 quantity = 2;
}

message ReserveStockResponse {
  bool isSuccess = 1;
  repeated RpcReservedStockItemDto items = 2;
  string errorMessage = 3;
}

message RpcReservedStockItemDto {
  int64 shopId = 1;
  string variantId = 2;
  int32 quantity = 3;
  int32 availableStocks = 4;
  string productName = 5;
  string variantName = 6;
  string unitPrice = 7;
}



