syntax = "proto3";

option csharp_namespace = "BuildingBlocks.Grpc.Services";

package seller;

service SellerGrpc {
  rpc ValidateShopOwner(ValidateShopOwnerRequest) returns (ValidateShopOwnerResponse);
  rpc GetShopsByIds(GetShopsByIdsRequest) returns (GetShopsByIdsResponse);
  rpc GetShopShippingInfo(GetShopShippingInfoRequest) returns (GetShopShippingInfoResponse);
}

message ValidateShopOwnerRequest {
  int64 shop_id = 1;
  int64 user_id = 2;
}

message ValidateShopOwnerResponse {
  bool is_owner = 1;
  string shop_name = 2;
  bool is_active = 3;
}

message GetShopsByIdsRequest {
  repeated int64 shop_ids = 1;
}

message ShopGrpcModel {
  int64 shop_id = 1;
  string name = 2;
}

message GetShopsByIdsResponse {
  repeated ShopGrpcModel shops = 1;
}

message GetShopShippingInfoRequest {
  int64 shop_id = 1;
}

message GetShopShippingInfoResponse {
  int64 shop_id = 1;
  string shop_name = 2;
  string phone = 3;
  string address_line = 4;
  int64 ward_id = 5;
  int64 district_id = 6;
  int64 province_id = 7;
  string ghn_shop_id = 8;
}
