#Mặc định gọi docker compose up -d sẽ gộp mặc định override vào 
services:
  product_db:
    container_name: ecommerce_product_db
    image: mysql:8.4
  
  cart_db:
    container_name: ecommerce_cart_db
    image: redis:7.4
    
  order_db:
    container_name: ecommerce_order_db
    image: postgres:16-alpine

  rabbitmq:
    container_name: ecommerce_rabbitmq
    image: rabbitmq:3-management

  identity_db:
    container_name: ecommerce_identity_db
    image: postgres:16-alpine

  payment_db:
    container_name: ecommerce_payment_db
    image: postgres:16-alpine

  seller_db:
    container_name: ecommerce_seller_db
    image: postgres:16-alpine

  shipping_db:
    container_name: ecommerce_shipping_db
    image: postgres:16-alpine

  elasticsearch:
    container_name: ecommerce_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0

  kibana:
    container_name: ecommerce_kibana
    image: docker.elastic.co/kibana/kibana:8.12.0