services:
  product_db:
    container_name: ecommerce_product_db
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ProductCatalogDb
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=123456

    ports:
      - "3308:3306"
    volumes:
      - mysql_product_data:/var/lib/mysql

  cart_db:
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_cart_data:/data

    #lệnh này ghì đè lệnh khởi động mặc định của container 
    #-> ghi nhớ các lệnh trước đó để thực hiện lại, vì khi stop sẽ mất hết dữ liệu do lưu trên Ram.
    command: redis-server --appendonly yes

  postgres_db:
    container_name: ecommerce_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=OrderDb
      - POSTGRES_MULTIPLE_DATABASES=IdentityDb,PaymentDb,SellerDb,ShippingDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_shared_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

  rabbitmq:
    container_name: ecommerce_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  elasticsearch:
    container_name: ecommerce_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    mem_limit: 1g

  kibana:
    container_name: ecommerce_kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    mem_limit: 512m

  minio:
    container_name: ecommerce_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    mem_limit: 256m

volumes:
  mysql_product_data:
    driver: local
  postgres_shared_data:
    driver: local
  redis_cart_data:
    driver: local
  elasticsearch_data:
    driver: local
  minio_data:
    driver: local
