name: 🔍 CI - Build Solution (.NET)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: 📦 Restore packages
        run: dotnet restore Microservices.sln

      - name: 🚀 Compile project
        run: dotnet build Microservices.sln --configuration Release --no-restore
